In [ ]:
# How to merge multiple csv files into one datafram and save to a csv file

In [20]:
import os
import glob
import pandas as pd
import csv
import pathlib

In [21]:
pwd

'C:\\Users\\collc\\OneDrive\\Desktop\\Data Analytics\\Tableau\\Resources\\Data\\Summer'

In [22]:
ls

 Volume in drive C is OS
 Volume Serial Number is 5AFF-6EBF

 Directory of C:\Users\collc\OneDrive\Desktop\Data Analytics\Tableau\Resources\Data\Summer

06/01/2021  07:10 PM    <DIR>          .
06/01/2021  07:10 PM    <DIR>          ..
05/30/2021  10:52 PM       405,357,734 citibike-tripdata-201906.csv
05/30/2021  10:51 PM       415,266,713 citibike-tripdata-201907.csv
05/30/2021  10:54 PM       445,923,019 citibike-tripdata-201908.csv
               3 File(s)  1,266,547,466 bytes
               2 Dir(s)  662,295,801,856 bytes free

In [23]:
os.chdir("/Users/collc/OneDrive/Desktop/Data Analytics/Tableau/Resources/Data/Summer")

In [24]:
pwd

'C:\\Users\\collc\\OneDrive\\Desktop\\Data Analytics\\Tableau\\Resources\\Data\\Summer'

In [25]:
ls

 Volume in drive C is OS
 Volume Serial Number is 5AFF-6EBF

 Directory of C:\Users\collc\OneDrive\Desktop\Data Analytics\Tableau\Resources\Data\Summer

06/01/2021  07:10 PM    <DIR>          .
06/01/2021  07:10 PM    <DIR>          ..
05/30/2021  10:52 PM       405,357,734 citibike-tripdata-201906.csv
05/30/2021  10:51 PM       415,266,713 citibike-tripdata-201907.csv
05/30/2021  10:54 PM       445,923,019 citibike-tripdata-201908.csv
               3 File(s)  1,266,547,466 bytes
               2 Dir(s)  662,295,519,232 bytes free

In [26]:
file_extension = ".csv"

In [27]:
all_filenames = [i for i in glob.glob(f"*{file_extension}")]

In [28]:
print(all_filenames)

['citibike-tripdata-201906.csv', 'citibike-tripdata-201907.csv', 'citibike-tripdata-201908.csv']

In [29]:
all_filenames = [i for i in glob.glob(f"*{file_extension}")]
all_data = (pd.read_csv(f, sep=',') for f in all_filenames)
merged_data = pd.concat(all_data, ignore_index=True)

In [30]:
combined_data = pd.DataFrame(merged_data)

In [31]:
combined_data.tail(10)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
6650648,532,2019-08-31 23:59:36.1200,2019-09-01 00:08:28.7850,3323.0,W 106 St & Central Park West,40.798186,-73.960591,3689.0,W 104 St & Amsterdam Ave,40.799041,-73.966495,33798,Subscriber,1989,2
6650649,838,2019-08-31 23:59:38.0510,2019-09-01 00:13:36.8530,3094.0,Graham Ave & Withers St,40.716981,-73.944859,3112.0,Milton St & Franklin St,40.729060,-73.957790,19826,Customer,1993,1
6650650,231,2019-08-31 23:59:39.0230,2019-09-01 00:03:30.4820,293.0,Lafayette St & E 8 St,40.730207,-73.991026,285.0,Broadway & E 14 St,40.734546,-73.990741,28225,Subscriber,1993,2
6650651,689,2019-08-31 23:59:41.4140,2019-09-01 00:11:10.8430,341.0,Stanton St & Mangin St,40.717821,-73.976289,439.0,E 4 St & 2 Ave,40.726281,-73.989780,32541,Subscriber,1988,2
6650652,1767,2019-08-31 23:59:45.7730,2019-09-01 00:29:13.6000,403.0,E 2 St & 2 Ave,40.725029,-73.990697,3141.0,1 Ave & E 68 St,40.765005,-73.958185,25832,Customer,1993,1
6650653,216,2019-08-31 23:59:46.2930,2019-09-01 00:03:23.0360,116.0,W 17 St & 8 Ave,40.741776,-74.001497,509.0,9 Ave & W 22 St,40.745497,-74.001971,38655,Subscriber,1972,1
6650654,117,2019-08-31 23:59:47.7970,2019-09-01 00:01:45.7440,3429.0,Hanson Pl & Ashland Pl,40.685068,-73.977908,353.0,S Portland Ave & Hanson Pl,40.685396,-73.974315,25264,Subscriber,1982,2
6650655,1614,2019-08-31 23:59:48.1560,2019-09-01 00:26:42.7760,387.0,Centre St & Chambers St,40.712733,-74.004607,3440.0,Fulton St & Adams St,40.692418,-73.989495,28485,Customer,1969,0
6650656,1301,2019-08-31 23:59:58.3620,2019-09-01 00:21:39.7040,3168.0,Central Park West & W 85 St,40.784727,-73.969617,423.0,W 54 St & 9 Ave,40.765849,-73.986905,38664,Customer,1969,0
6650657,419,2019-08-31 23:59:59.4520,2019-09-01 00:06:59.0210,447.0,8 Ave & W 52 St,40.763707,-73.985162,529.0,W 42 St & 8 Ave,40.757570,-73.990985,35210,Subscriber,1994,1

In [32]:
combined_data.describe()

,tripduration,start station id,start station latitude,start station longitude,end station id,end station latitude,end station longitude,bikeid,birth year,gender
count,6.650658e+06,6.650515e+06,6.650658e+06,6.650658e+06,6.650515e+06,6.650658e+06,6.650658e+06,6.650658e+06,6.650658e+06,6.650658e+06
mean,1.064229e+03,1.675524e+03,4.073682e+01,-7.398187e+01,1.671561e+03,4.073648e+01,-7.398200e+01,2.896740e+04,1.980648e+03,1.156331e+00
std,1.224107e+04,1.477822e+03,3.077123e-02,2.035147e-02,1.478369e+03,3.072060e-02,2.045983e-02,7.454483e+03,1.198337e+01,5.642781e-01
min,6.100000e+01,7.200000e+01,4.065540e+01,-7.402535e+01,7.200000e+01,4.065540e+01,-7.406860e+01,1.452900e+04,1.885000e+03,0.000000e+00
25%,3.890000e+02,3.820000e+02,4.071689e+01,-7.399596e+01,3.800000e+02,4.071625e+01,-7.399612e+01,2.169800e+04,1.970000e+03,1.000000e+00
50%,6.720000e+02,5.140000e+02,4.073705e+01,-7.398518e+01,5.140000e+02,4.073625e+01,-7.398565e+01,3.033200e+04,1.983000e+03,1.000000e+00
75%,1.180000e+03,3.296000e+03,4.075725e+01,-7.397101e+01,3.298000e+03,4.075715e+01,-7.397101e+01,3.423300e+04,1.990000e+03,1.000000e+00
max,3.812666e+06,3.810000e+03,4.086900e+01,-7.387800e+01,3.810000e+03,4.086900e+01,-7.387800e+01,4.002500e+04,2.003000e+03,2.000000e+00

In [33]:
combined_data['gender'] = combined_data['gender'].replace([0, 1, 2],['Undisclosed','Male','Female'])

In [34]:
combined_data.tail(10)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
6650648,532,2019-08-31 23:59:36.1200,2019-09-01 00:08:28.7850,3323.0,W 106 St & Central Park West,40.798186,-73.960591,3689.0,W 104 St & Amsterdam Ave,40.799041,-73.966495,33798,Subscriber,1989,Female
6650649,838,2019-08-31 23:59:38.0510,2019-09-01 00:13:36.8530,3094.0,Graham Ave & Withers St,40.716981,-73.944859,3112.0,Milton St & Franklin St,40.729060,-73.957790,19826,Customer,1993,Male
6650650,231,2019-08-31 23:59:39.0230,2019-09-01 00:03:30.4820,293.0,Lafayette St & E 8 St,40.730207,-73.991026,285.0,Broadway & E 14 St,40.734546,-73.990741,28225,Subscriber,1993,Female
6650651,689,2019-08-31 23:59:41.4140,2019-09-01 00:11:10.8430,341.0,Stanton St & Mangin St,40.717821,-73.976289,439.0,E 4 St & 2 Ave,40.726281,-73.989780,32541,Subscriber,1988,Female
6650652,1767,2019-08-31 23:59:45.7730,2019-09-01 00:29:13.6000,403.0,E 2 St & 2 Ave,40.725029,-73.990697,3141.0,1 Ave & E 68 St,40.765005,-73.958185,25832,Customer,1993,Male
6650653,216,2019-08-31 23:59:46.2930,2019-09-01 00:03:23.0360,116.0,W 17 St & 8 Ave,40.741776,-74.001497,509.0,9 Ave & W 22 St,40.745497,-74.001971,38655,Subscriber,1972,Male
6650654,117,2019-08-31 23:59:47.7970,2019-09-01 00:01:45.7440,3429.0,Hanson Pl & Ashland Pl,40.685068,-73.977908,353.0,S Portland Ave & Hanson Pl,40.685396,-73.974315,25264,Subscriber,1982,Female
6650655,1614,2019-08-31 23:59:48.1560,2019-09-01 00:26:42.7760,387.0,Centre St & Chambers St,40.712733,-74.004607,3440.0,Fulton St & Adams St,40.692418,-73.989495,28485,Customer,1969,Undisclosed
6650656,1301,2019-08-31 23:59:58.3620,2019-09-01 00:21:39.7040,3168.0,Central Park West & W 85 St,40.784727,-73.969617,423.0,W 54 St & 9 Ave,40.765849,-73.986905,38664,Customer,1969,Undisclosed
6650657,419,2019-08-31 23:59:59.4520,2019-09-01 00:06:59.0210,447.0,8 Ave & W 52 St,40.763707,-73.985162,529.0,W 42 St & 8 Ave,40.757570,-73.990985,35210,Subscriber,1994,Male

In [35]:
shape = combined_data.shape

In [36]:
shape

(6650658, 15)

In [37]:
combined_data.to_csv("Citibike_Data_Summer2019.csv", index=False)